version: '3.9'
services:
  web-server:
    image: nginx:1.21.3-alpine
    container_name: nginx_web
    command: [nginx-debug, '-g', 'daemon off;']    
    ports:
    - 80:80
    - 443:443
    restart: unless-stopped
    volumes:
    - ./conf/default.conf:/etc/nginx/conf.d/default.conf
    networks:
    - outnet
    - innet

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
    - 3000:3000
    networks:
    - innet
    depends_on:
    - web-server
    volumes:
    - ./provisioning/:/etc/grafana/provisioning/datasources/
    - ./dashboards/:/etc/grafana/provisioning/dashboards/
    - ./dashboards/node-exporter-full_rev31.json:/var/lib/grafana/dashboards/node-exporter-full_rev31.json
    - grafana-storage:/var/lib/grafana
    - ./conf/grafana.ini:/etc/grafana/grafana.ini

    environment:
    - GF_SECURITY_ADMIN_USER=test
    - GF_SECURITY_ADMIN_PASSWORD=asd123

  db:
    image: postgres:latest
    container_name: postgre_db
    restart: unless-stopped
    volumes:
    - db_postgre:/var/lib/postgresql/data
    networks:
    - innet
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=jbpm
    - POSTGRES_USER=jbpm
    - POSTGRES_PASSWORD=jbpm
    depends_on:
    - web-server

  jbpm:
    image: jboss/jbpm-server-full:latest
    container_name: jbpm
    restart: always
    environment:
    - JBPM_DB_DRIVER=postgre
    - JBPM_DB_NAME=jbpm
    - JBPM_DB_USER=jbpm
    - JBPM_DB_PASSWORD=jbpm
    volumes:
    - jmbp_volume:/opt/jboss/wildfly/bin/.niogit:Z
    ports:
    - 8000:8080
    - 8001:8001 
    networks:
    - innet
    depends_on:
    - db
    - web-server

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    networks:
      - innet
    depends_on:
    - web-server

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    networks:
      - innet
    depends_on:
    - web-server  


networks:
  outnet:
    name: outnet
    driver: bridge
  innet:
    name: innet
    driver: bridge

volumes:
  db_postgre:
  jmbp_volume:
  prometheus_data:
  grafana-storage:
