version: '3.9'
services:
  web-server:
    image: nginx:1.21.3-alpine
    container_name: nginx_web
    command: [nginx-debug, '-g', 'daemon off;']    
    ports:
    - 80:80
    - 443:443
    restart: unless-stopped
    volumes:
    - ./conf/default.conf:/etc/nginx/conf.d/default.conf

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
    - 3000:3000
    depends_on:
    - web-server
    volumes:
    - ./provisioning/:/etc/grafana/provisioning/datasources/
    - ./dashboards/:/etc/grafana/provisioning/dashboards/
    - ./dashboards/node-exporter-full_rev31.json:/var/lib/grafana/dashboards/node-exporter-full_rev31.json
    - grafana-storage:/var/lib/grafana
    - ./conf/grafana.ini:/etc/grafana/grafana.ini
    environment:
    - GF_SECURITY_ADMIN_USER=test
    - GF_SECURITY_ADMIN_PASSWORD=test

  db:
    image: postgres:latest
    container_name: postgre_db
    restart: unless-stopped
    volumes:
    - db_postgre:/var/lib/postgresql/data
    ports:
    - 5432:5432
    environment:
    - POSTGRES_DB=admin_postgres
    - POSTGRES_USER=admin_postgres
    - POSTGRES_PASSWORD=admin_postgres
    depends_on:
    - web-server

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    depends_on:
    - web-server

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - 9090:9090
    depends_on:
    - web-server
    
  adminer:
    container_name: adminer
    image: adminer
    restart: always

volumes:
  db_postgre:
  prometheus_data:
  grafana-storage:
